# Simulation Parameters
dim: 2
n_grid: 128
max_steps: 2048
steps: 1024
dt: 0.001
gravity: 3.8

# Training Parameters
iters: 100
learning_rate: 0.1
actuation_omega: 20
act_strength: 4

# Scene Parameters
scene_type: "robot" # options: robot, fish
